# Generated by Django 4.2.7 on 2023-12-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_acccounts', '0002_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
